apiVersion: apps/v1
kind: Deployment	      
metadata:
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      imagePullSecrets:
        - name: harbor-admin-registry
      containers:
      - name: demo-app
        image: harbor.group3.class/demo-app:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service		      
metadata:
  name: demo-app
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: demo-app
  type: ClusterIP

